version: '3'
services: 
    sql_server:
        container_name: sql_server
        image: microsoft/mssql-server-linux:2017-latest
        restart: always
        ports:
            - 1533:1433
        volumes: 
            - ms-db:/data 
        environment: 
           - ACCEPT_EULA=Y
           - MSSQL_SA_PASSWORD=abc#1234
    
    spring_service:
        depends_on: 
            - sql_server
        build: .
        ports: 
            - 8553:8443
        environment:
             SPRING_DATASOURCE_URL: jdbc:sqlserver://sql_server:1433;databaseName=test1
volumes: 
    ms-db:
        driver: local
        